language: bash
dist: trusty
sudo: required
notifications:
  email: false

before_install:
- git clone https://github.com/staticlibs/android-ndk-r9d-arm-linux-androideabi-4.8.git
- pwd
- dir
- cd android-ndk-r9d-arm-linux-androideabi-4.8
- dir
- cd ../

script:
- 'git clone https://github.com/u125300/ntvl.git'
- 'dir'
- 'cd ntvl'
- 'mkdir build'
- 'cd build'
- 'cmake ..'
- 'make'
- 'tar -czvf ntvl_droid_.tar.gz *'
- 'curl -T ntvl_droid_.tar.gz -u yzcmjsn@gmail.com:0339109523 https://dav.box.com/dav/android_/'
