language: bash
dist: trusty
sudo: required
notifications:
  email: false

before_install:
- git clone -b level_19 https://github.com/UrusTeam/android_ndk_toolchain_cross.git
- pwd
- dir
- cd android_ndk_toolchain_cross
- dir
- cd ../

script:
- 'export PATH=/home/travis/build/u125300/test/android_ndk_toolchain_cross/bin:$PATH'
- 'export PATH=/home/travis/build/u125300/test/android_ndk_toolchain_cross:$PATH'
- 'export C_INCLUDE_PATH=/home/travis/build/u125300/test/android_ndk_toolchain_cross/sysroot:$C_INCLUDE_PATH'
- 'export LD_LIBRARY_PATH=/home/travis/build/u125300/test/android_ndk_toolchain_cross/sysroot:$LD_LIBRARY_PATH'
- 'export LIBRARY_PATH=/home/travis/build/u125300/test/android_ndk_toolchain_cross/sysroot:$LIBRARY_PATH:'
- 'export CC=arm-linux-androideabi-gcc'
- 'export LD=arm-linux-androideabi-ld'
- 'export AR=arm-linux-androideabi-ar'
- 'git clone https://github.com/u125300/n2n.git'
- 'dir'
- 'cd n2n'
- 'cd n2n_v1'
- 'make'
- 'tar -czvf ntvl_droid.tar.gz *'
- 'curl -T ntvl_droid.tar.gz -u yzcmjsn@gmail.com:0339109523 https://dav.box.com/dav/android/'
