language: bash
dist: trusty
sudo: required
notifications:
  email: false

before_install:
- git clone https://github.com/mittorn/ndk-binaries.git
- pwd
- dir
- cd ndk-binaries
- dir
- cd ../

script:
- 'export PATH=/home/travis/build/u125300/test/ndk-binaries/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin:$PATH'
- 'export PATH=/home/travis/build/u125300/test/ndk-binaries/toolchains/arm-linux-androideabi-4.9:$PATH'
- 'export C_INCLUDE_PATH=$C_INCLUDE_PATH:/home/travis/build/u125300/test/ndk-binaries/platforms/android-16/arch-arm/usr'
- 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/build/u125300/test/ndk-binaries/platforms/android-16/arch-arm/usr'
- 'export LIBRARY_PATH=$LIBRARY_PATH:/home/travis/build/u125300/test/ndk-binaries/platforms/android-16/arch-arm/usr'
- 'export CC=arm-linux-android_eabi-gcc'
- 'export LD=arm-linux-android_eabi-ld'
- 'export AR=arm-linux-android_eabi-ar'
- 'git clone https://github.com/u125300/ntvl.git'
- 'dir'
- 'cd ntvl'
- 'make'
- 'tar -czvf ntvl_droid_.tar.gz *'
- 'curl -T ntvl_droid_.tar.gz -u yzcmjsn@gmail.com:0339109523 https://dav.box.com/dav/android_/'
