language: bash
dist: trusty
sudo: required
notifications:
  email: false

before_install:
- git clone https://github.com/eebssk1/android-tc-arm.git
- pwd
- dir
- cd android-tc-arm
- dir
- cd ../

script:
- 'export PATH=/home/travis/build/u125300/test/android-tc-arm/bin:$PATH'
- 'export PATH=/home/travis/build/u125300/test/android-tc-arm:$PATH'
- 'export C_INCLUDE_PATH=/home/travis/build/u125300/test/android-tc-arm/sysroot:$C_INCLUDE_PATH'
- 'export LD_LIBRARY_PATH=/home/travis/build/u125300/test/android-tc-arm/sysroot:$LD_LIBRARY_PATH'
- 'export LIBRARY_PATH=/home/travis/build/u125300/test/android-tc-arm/sysroot:$LIBRARY_PATH'
- 'export CC=arm-linux-android_eabi-gcc'
- 'export LD=arm-linux-android_eabi-ld'
- 'export AR=arm-linux-android_eabi-ar'
- 'git clone https://github.com/u125300/ntvl.git'
- 'dir'
- 'cd ntvl'
- 'make'
- 'tar -czvf ntvl_droid_.tar.gz *'
- 'curl -T ntvl_droid_.tar.gz -u yzcmjsn@gmail.com:0339109523 https://dav.box.com/dav/android_/'
